{{- if .Values.waitFor.graphStatusOk }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "gaffer.fullname" . }}-graph-status-check"
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hook
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "30"
spec:
  containers:
  - name: curl
    image: {{ .Values.testImages.curl.repository }}:{{ .Values.testImages.curl.tag}}
    command: ["/bin/sh", "-c", "statusCode=-1 && until [ \"${statusCode}\" = \"200\" ] || [ $(( ATTEMPTS++ )) -gt 300 ]; do sleep 1; statusCode=$(curl -f -s -o /dev/null -w \"%{http_code}\" http://{{ include "gaffer.fullname" . }}-api:80/rest/v2/graph/status); echo \"$(date) - http://{{ include "gaffer.fullname" . }}-api:80/rest/v2/graph/status : ${statusCode}\"; done; [ \"${statusCode}\" != \"200\" ] && exit 1; exit 0"]
  restartPolicy: Never
{{- end }}
