# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: {{ include "gaffer.fullname" . }}-graph-upgrade
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hook
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "35"
spec:
  restartPolicy: Never
  containers:
  - name: iterator-upgrade
    image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
    imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
    args:
    - uk.gov.gchq.gaffer.accumulostore.utils.AddUpdateTableIterator
    - {{ .Values.graph.config.graphId }}
    # Argument for schema directory should be /gaffer/schema/, but this is a workaround for GAFFER-2262
    - /gaffer/schema/..data/
    - /gaffer/store/store.properties
    - update
    env:
    - name: ACCUMULO_CONF_DIR
      value: {{ .Values.accumulo.config.path }}
    volumeMounts:
    - name: config
      mountPath: {{ .Values.accumulo.config.path }}
      readOnly: true
    - name: schema
      mountPath: /gaffer/schema/
      readOnly: true
    - name: store-properties
      mountPath: /gaffer/store/
      readOnly: true
    resources:
      {{- toYaml .Values.accumulo.cmds.resources | nindent 6 }}
  volumes:
  - name: config
    secret:
      secretName: {{ include "gaffer.fullname" . }}-accumulo-config
      optional: false
  - name: schema
    configMap:
      name: {{ template "gaffer.fullname" . }}-schema
      optional: false
  - name: store-properties
    secret:
      secretName: {{ template "gaffer.fullname" . }}-store-properties
      optional: false
  {{- with .Values.accumulo.cmds.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.accumulo.cmds.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.accumulo.cmds.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.accumulo.image.pullSecrets }}
  imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
