# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "gaffer.fullname" . }}-app
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: gaffer-app
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.pathPrefix.api }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "gaffer.fullname" . }}-api
            port: 
              name: http
{{- else }}
        backend:
          serviceName: {{ include "gaffer.fullname" . }}-api
          servicePort: http
{{- end }}
      - path: {{ .Values.ingress.pathPrefix.ui }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "gaffer.fullname" . }}-ui
            port: 
              name: http
{{- else }}
        backend:
          serviceName: {{ include "gaffer.fullname" . }}-ui
          servicePort: http
{{- end }}
{{- if ne .Values.ingress.host "" }}
    host: {{ .Values.ingress.host }}
{{- end }}
{{- end }}
