releasenotes:
  sections:
  - title: "Headliners"
    emoji: ":star:"
    labels: [ "headliner" ]
  - title: "New Features"
    emoji: ":gift:"
    labels: [ "feature" ]
  - title: "Enhancements"
    emoji: ":sparkles:"
    labels: [ "enhancement" ]
  - title: "Bugs Fixed"
    emoji: ":beetle:"
    labels: [ "bug" ]
  - title: "Documentation"
    emoji: ":book:"
    labels: "documentation"
  - title: "Automation"
    emoji: ":robot:"
    labels: [ "automation" ]
