#!/usr/bin/env python

import requests

data = """
{
    "elements": [
	{
	    "class": "gaffer.data.element.Edge",
	    "properties": {
		"count": 1
	    },
	    "group": "edge",
	    "source": "bristol",
	    "destination": "birmingham",
	    "directed": true
	},
	{
	    "class": "gaffer.data.element.Edge",
	    "properties": {
		"count": 1
	    },
	    "group": "edge",
	    "source": "bristol",
	    "destination": "exeter",
	    "directed": true
	},
	{
	    "class": "gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "entity",
	    "vertex": "bristol"
	},
        {
	    "class": "gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "entity",
	    "vertex": "birmingham"
	},
        {
	    "class": "gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "entity",
	    "vertex": "exeter"
	}
    ]
}
"""

url = "http://localhost:8080/rest/v1/graph/doOperation/add/elements"

response = requests.put(url, data, headers={'content-type':'application/json'})

print "Status:",response.status_code
print response.text

