#!/usr/bin/env python

import requests

data = '{}'

url = 'http://localhost:8080/rest/v1/graph/doOperation/get/elements/all'

response = requests.post(url, data,
                         headers={'content-type': 'application/json'})

print "Status:",response.status_code
print response.text

