#!/bin/bash

# Simple script, starts the containers needed to run Gaffer.
#
# Copyright 2016 Crown Copyright, cybermaggedon
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Location for persistent data
data_dir=/data

# Initialise data directory for Hadoop, ZK, Accumulo
mkdir -p ${data_dir}/hadoop
mkdir -p ${data_dir}/zookeeper
mkdir -p ${data_dir}/accumulo

# May be needed on your system to keep SElinux happy.
#chcon -Rt svirt_sandbox_file_t /data

# Run Hadoop
docker run -d --name hadoop -v ${data_dir}/hadoop:/data \
       cybermaggedon/hadoop:2.7.3

# Run Zookeeper
docker run -d --name zookeeper -v ${data_dir}/zookeeper:/data \
       cybermaggedon/zookeeper:3.4.9

# Run Accumulo
docker run -d --name accumulo -v ${data_dir}/accumulo:/accumulo \
       --link zookeeper:zookeeper \
       --link hadoop:hadoop gchq/accumulo-gaffer:0.4.4g

# Run Wildfly, exposing port 8080.
docker run -d --name wildfly --link zookeeper:zookeeper \
       --link hadoop:hadoop --link accumulo:accumulo \
       -p 8080:8080 gchq/wildfly-gaffer:0.4.4g

