#!/bin/bash

# Location for persistent data
data_dir=/data

# Initialise data directory for Hadoop, ZK, Accumulo
mkdir -p ${data_dir}/hadoop
mkdir -p ${data_dir}/zookeeper
mkdir -p ${data_dir}/accumulo

# May be needed on your system to keep SElinux happy.
#chcon -Rt svirt_sandbox_file_t /data

# Run Hadoop
docker run -d --name hadoop -v ${data_dir}/hadoop:/data \
       cybermaggedon/hadoop:2.7.3

# Run Zookeeper
docker run -d --name zookeeper -v ${data_dir}/zookeeper:/data \
       cybermaggedon/zookeeper:3.4.9

# Run Accumulo
docker run -d --name accumulo -v ${data_dir}/accumulo:/accumulo \
       --link zookeeper:zookeeper \
       --link hadoop:hadoop cybermaggedon/accumulo-gaffer:0.4.4c

# Run Wildfly, exposing port 8080.
docker run -d --name wildfly --link zookeeper:zookeeper \
       --link hadoop:hadoop --link accumulo:accumulo \
       -p 8080:8080 cybermaggedon/wildfly-gaffer:0.4.4c

