{{- if or .Values.accumulo.config.userManagement.users .Values.accumulo.config.postInstallCommands }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "gaffer.fullname" . }}-accumulo-post-install-cmds
  annotations:
    helm.sh/hook: post-install,post-upgrade
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: post-install-cmds
spec:
  restartPolicy: Never
  containers:
  - name: cmds
    image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
    imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
    command: ["/bin/bash", "/cmds/run.sh"]
    env:
    - name: ACCUMULO_CONF_DIR
      value: /etc/accumulo/
    volumeMounts:
    - name: config
      mountPath: /etc/accumulo/
      readOnly: true
    - name: cmds
      mountPath: /cmds
      readOnly: true
    resources:
      {{- toYaml .Values.accumulo.cmds.resources | nindent 10 }}
  volumes:
  - name: config
    secret:
      secretName: {{ include "gaffer.fullname" . }}-accumulo-config
      optional: false
  - name: cmds
    secret:
      secretName: {{ include "gaffer.fullname" . }}-accumulo-cmds
      optional: false
  {{- with .Values.accumulo.cmds.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.accumulo.cmds.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.accumulo.cmds.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.accumulo.image.pullSecrets }}
  imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
