{{- if or .Values.accumulo.config.users .Values.accumulo.config.postInstallCommands }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gaffer.fullname" . }}-post-install-cmds
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: post-install-cmds
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        {{- include "gaffer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: post-install-cmds
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cmds
        image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
        imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
        command: ["/bin/bash", "/cmds/run.sh"]
        env:
        - name: ACCUMULO_CONF_DIR
          value: /etc/accumulo/
        volumeMounts:
        - name: config
          mountPath: /etc/accumulo/
          readOnly: true
        - name: cmds
          mountPath: /cmds
          readOnly: true
        resources:
          {{- toYaml .Values.accumulo.cmds.resources | nindent 10 }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "gaffer.fullname" . }}-accumulo-config
          optional: false
      - name: cmds
        secret:
          secretName: {{ include "gaffer.fullname" . }}-post-install-cmds
          optional: false
      {{- with .Values.accumulo.cmds.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.cmds.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.cmds.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
{{- end }}

