{{- define "gaffer.accumuloCommandsScript" -}}
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

USERNAME=$(cat ${ACCUMULO_CONF_DIR}/client.conf | grep "auth.principal" | grep -v "^#" | cut -d= -f2)
PASSWORD=$(cat ${ACCUMULO_CONF_DIR}/client.conf | grep "auth.token" | grep -v "^#" | cut -d= -f2)
[[ -z "${USERNAME}" || -z "${PASSWORD}" ]] && echo "Unable to locate Accumulo username and password in ${ACCUMULO_CONF_DIR}/client.conf" && exit 1

accumulo shell -fv ./commands.txt -u ${USERNAME} -p ${PASSWORD} <<EOF
{{- range $username := (keys .Values.accumulo.config.users | sortAlpha) }}
{{- $userInfo := index $.Values.accumulo.config.users $username }}
{{ required (print "Password required for Accumulo User: " $username ". Please set: accumulo.config.users." $username ".password") $userInfo.password }}
{{ $userInfo.password }}
{{- end }}
EOF
{{- end -}}

{{- define "gaffer.accumuloCommandsFile" -}}
  {{- range $username := (keys .Values.accumulo.config.users | sortAlpha) }}
    {{- $userInfo := index $.Values.accumulo.config.users $username }}
    {{- printf "createuser %s" $username }}
    {{- if $userInfo.permissions }}
      {{- if $userInfo.permissions.system }}
        {{- range $permission := $userInfo.permissions.system }}
          {{- printf "grant %s -s -u %s" $permission $username | nindent 0 }}
        {{- end }}
      {{- end }}
      {{- if $userInfo.permissions.table }}
        {{- range $table, $permissions := $userInfo.permissions.table }}
          {{- range $permission := $permissions }}
            {{- printf "grant %s -t %s -u %s" $permission $table $username | nindent 0 }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if $userInfo.auths }}
      {{- printf "addauths -s %s -u %s" ($userInfo.auths | join ",") $username | nindent 0 }}
    {{- end }}
  {{- end }}

  {{- range $cmd := .Values.accumulo.config.postInstallCommands }}
    {{- print $cmd | nindent 0 }}
  {{- end }}
  {{- print "exit" | nindent 0 }}
{{- end -}}

{{- if or .Values.accumulo.config.users .Values.accumulo.config.postInstallCommands }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gaffer.fullname" . }}-post-install-cmds
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
type: Opaque
data:
  run.sh: {{ include "gaffer.accumuloCommandsScript" . | b64enc }}
  commands.txt: {{ include "gaffer.accumuloCommandsFile" . | b64enc }}
{{- end }}

