# DELETE WHEN BUILDING OK

version: "3.7"

services:

  gaffer-rest:
    image: gchq/gaffer-rest-krb:${GAFFER_VERSION}-${ACCUMULO_VERSION}
    entrypoint: sleep 600
    build:
      context: .
      args:
        BASE_IMAGE_NAME: gchq/gaffer-rest
        BASE_IMAGE_TAG: ${GAFFER_VERSION}-${ACCUMULO_VERSION}
    ports:
      - 8080:8080
    container_name: gaffer-rest
