# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

nameOverride: ""
fullnameOverride: ""

hdfs:
  enabled: true
  config:
    hdfsSite:
      dfs.datanode.synconclose: true
  volumes:
  - /accumulo
  namenode:
    hostname: "" # Only needs to be set if hdfs.enabled = false
    ports:
      clientRpc: 8020
  postInstallCommands:
  - hadoop fs -mkdir -p /accumulo
  - hadoop fs -chown accumulo /accumulo
  - hadoop fs -chmod 700 /accumulo
  - hadoop fs -ls /

zookeeper:
  enabled: true
  externalHosts: ""
  replicaCount: 1

instanceId: accumulo
config:
  path: /etc/accumulo/conf
  files: {}
  accumuloSite:
    instance.secret: "DEFAULT"
    tserver.memory.maps.native.enabled: true
    tserver.memory.maps.max: 128M
    tserver.cache.data.size: 15M
    tserver.cache.index.size: 40M
    tserver.total.mutation.queue.max: 16M
    tserver.sort.buffer.size: 50M
    tserver.walog.max.size: 128M
  userManagement:
    rootPassword: "root"
    # If accumulo.config.userManagement.revoke.enabled is:
    # true - Any users or permissions not specified below will be removed
    # false - Only missing users and permissions will be added
    revoke:
      enabled: true
    users:
      tracer:
        password: "tracer"
        permissions:
          system:
          - CREATE_TABLE
          table:
            trace:
            - READ
            - WRITE
      
  postInstallCommands: []

image:
  repository: gchq/accumulo
  tag: 1.9.3
  pullPolicy: IfNotPresent
  pullSecrets: []

master:
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

tabletServers:
  replicaCount: 3
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

gc:
  replicaCount: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

cmds:
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

monitor:
  replicaCount: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    host: ""
    # For Traefik:
    #pathPrefix: /accumulo/
    # For Nginx:
    pathPrefix: "/accumulo/(.*)"
