apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gaffer-jhub.optionsServerServiceAccountName" . }}
  labels:
    {{- include "gaffer-jhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: options-server
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "persistentvolumeclaims"
  - "serviceaccounts"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "secrets"
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "patch"
  - "update"
- apiGroups:
  - "extensions"
  resources:
  - "ingresses"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "patch"
  - "update"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "patch"
  - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gaffer-jhub.optionsServerServiceAccountName" . }}
  labels:
    {{- include "gaffer-jhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: options-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gaffer-jhub.optionsServerServiceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gaffer-jhub.optionsServerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
