api:
  user: root

test:
  runIntegrationTests: true

accumulo:
  hdfs:
    postInstallCommands:
    - hadoop fs -chmod 777 /
  enabled: true
  config:
    postInstallCommands:
    - setauths -u root -s vis1,vis2,publicVisibility,privateVisibility,public,private